### ISSUE TITLE
drush remote command stderr output winds up on stdout locally

### ISSUE THREAD

**Issue by mc0e** [drush-ops/drush#1270]
I'm trying to script some stuff and I have a command (with bash variables) like so:

```
directory=$(drush @$alias drupal-directory $module)
```

I'm running a lot of remote commands, so to make it a bit quicker I'm running over persistent ssh 'Master' connections to each server involved.  The problem is that this results in a message about the connection winding up in my $directory variable.  e.g. in the following command all of the output is on stdout:

```
drush @$alias drupal-directory webform

/var/local/www/example.com/htdocs/sites/all/modules/contrib/webform
Shared connection to 1.2.3.4 closed.
```

SSH puts that output onto stderr though, and it's the local drush command that reroutes it to stderr.

Could drush be changed to not do that, and let stderr output stay on stderr?  It's then up to whatever calls drush to combine the two if that's desired.

**Comment by weitzman** [comment]
This is likely a dupe. Maybe @greg-1-anderson knows the right issue for this.

**Comment by greg-1-anderson** [comment]
This has been discussed in [Improve Drush's handling of STDERR in backend invoke](https://www.drupal.org/node/1721586) [Reduce complexity of backend invoke; consider removing concurrency](https://www.drupal.org/node/1982502).  This issue can now serve as the official discussion point for stderr issues moving forward.

This change was controversial for a number of reasons.

1) Aegir wants to be able to pipe `drush | drush` in backend mode, so separating the log messages to stderr would interfere with this.  Since Drush removes the log messages from the IO stream anyway, we could just leave the log messages on stdout, and leave other stderr messages on stderr.

2) If we did not redirect stderr to stdout, we'd need to handle two streams in backend invoke.  There was some pushback about making backend invoke more complicated than it already is.

3) There would also be interoperability issues if there were different versions of Drush running on the local and remote ends of a communication stream.  Backwards compatibility could be maintained, optionally, but that would entail more complexity.

Despite all of this, I think it would be a benefit to straighten out Drush's use of stdout and stderr at some point.  However, changing backend invoke is complicated, and may continue to be controversial.  We can't make this sort of change in the middle of a stable release of Drush, and we are presently planning on releasing Drush 7.0-rc1 tomorrow.

We could release 7.0-alpha10 tomorrow instead, and fix stderr now, or put this off until Drush 8, sometime after we make and diverge the 7.x branch from master.  I can start working on this right away if desired, but perhaps deferral (again!) is the more prudent option.

**Comment by greg-1-anderson** [comment]
cc @anarcat  @msonnabaum @grugnog @juampy72

**Comment by mc0e** [comment]
Well, I guess it's unsurprising that I'd favour doing it as part of the current release cycle.

I think you've answered issue 1.  

I'm guessing the code involved in issue 2 is likely not to be code many people need to look at much, but maybe I just don't know what I'm talking about there?  Balance this against simplification of any code that handles the output(s) of drush.

The backwards compatibility issue is important.  People will have need of scripting control of multiple remote servers, and it will in many cases be infeasible to update some of them.  Points to note include that 1) there is already an incompatibility betwen the behaviours of drush run against a local alias and against a remote one, and 2) the "fix" to combine the two streams is particularly simple to do on the output of the local drush command.

**Comment by weitzman** [comment]
I agree that this would be nice to straighten out. My priority list for backend is at #/975. So it might take a while for a Drush maintainer to get to this.

**Comment by greg-1-anderson** [comment]
I sort of think that stderr should be fixed before we remove concurrency (and the related / dependent feature, alias lists).  There are some folks who still find some utility in concurrency, so I think we should move slowly here.

Fixing stderr seems more urgent to me -- but I still think Drush 8 is probably the better time to do this.

**Comment by juampy72** [comment]
Thanks for keeping me on the loop but I am involved in other things and can't look at it. I will follow the discussion, though.

**Comment by mc0e** [comment]
* What's the timeframe for Drush 8 likely to be like?
* What are the interim options?  Could this functionality be written into a module somehow, providing an alternative way to forward requests to remote servers, or would it need to be maintained as a patch?

**Comment by greg-1-anderson** [comment]
The thing about this issue is that it involves the core of backend invoke, and you can't really touch that in any way without affecting compatibility (or risk thereof) with the Drush on the other end.  This could not be implemented as a hook or a patch.

We will create the Drush 7.x branch when someone submits a PR that breaks backwards compatibility with the 7.x releases.  At that point, "master" will become 8.x.  Ideally, this wouldn't happen until a while after Drush 7 stable is released.

**Comment by thomscode** [comment]
Has this ever made any progress? I'm working with Drush 8 and it seems to still have the same problem.

**Comment by thomscode** [comment]
This diff (for Drush 8) works for me to separate out STDOUT from STDERR on remote drush calls, but I don't know what other ramifications this will have. Is this something that can be added as a pull request? Or are there reasons not to be doing this?

https://gist.github.com/thomscode/a8f23f2e534844ede58bd93132ec5f03

**Comment by greg-1-anderson** [comment]
Well, that's certainly a start. Do log messages still work on remote calls? i.e. do you still see log messages appear incrementally when doing things like `site-install` on a remote target?

It would be kind of ironic if this was all that was left. I did some work on straightening this out years ago in Drush 5, but nothing has happened since then. Create a PR and see if any tests fail.

**Comment by thomscode** [comment]
I've never tried `site-install` on a remote target, but I'll create the PR and see what the tests say. I am writing a CI script using Robo and Drush so I'll give the remote `site-install` a try and see what if I have any differences with/without the patch.

**Comment by greg-1-anderson** [comment]
Any command that produces output slowly over time (e.g. updatedb when there are a lot of updates) will do for that test.

**Comment by thomscode** [comment]
Thanks for the tip. The CI tests failed for the PR, but it definitely gave me somewhere to look, as there are 3 distinct things that need addressed. One looks like it may simply need the test updated not to look for the redirection, but I'm not sure about the others.

I'll take a look at those and see what I can find out.

Thanks again for the direction on what to look for and how to test.

**Comment by thomscode** [comment]
I was able to fix one of the tests, and still need to work on the others. I was able to run a `site-install` over SSH and here is the result:

**Normal `site-install`**
```
***************************************************************************
                              NOTICE TO USERS

This is a Federal computer system and is the property of the United
States Government. It is for authorized use only. Users (authorized or
unauthorized) have no explicit or implicit expectation of privacy.

Any or all uses of this system and all files on this system may be
intercepted, monitored, recorded, copied, audited, inspected, and disclosed
to authorized site, Department of Energy, and law enforcement personnel,
as well as authorized officials of other agencies, both domestic and
foreign. By using this system, the user consents to such interception,
monitoring, recording, copying, auditing, inspection, and disclosure at the
discretion of authorized site or Department of Energy personnel.

Unauthorized or improper use of this system may result in administrative
disciplinary action and civil and criminal penalties. By continuing to use
this system you indicate your awareness of and consent to these terms and
conditions of use.

By logging on to this system you agree to the above terms and conditions.

***************************************************************************

You are about to DROP all tables in your 'phoenix_stage' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the        [ok]
--notify global option.
Installation complete.  User name: ***********  User password:              [ok]
********
```

**STDERR Redirected `site-install`**
```
You are about to DROP all tables in your 'phoenix_stage' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the        [ok]
--notify global option.
Installation complete.  User name: ***********  User password:              [ok]
********
```

As you can see in my case we have a "Federal computer system" disclaimer that is output on `STDERR` when connecting via SSH (which is what I'm trying to avoid having in my output for commands with `--pipe` option). With the patch applied, the `STDOUT` no longer has the disclaimer but still receives the `ok` log messages from `site-install`.

Is this what you would expect/want the output to be?

**Comment by greg-1-anderson** [comment]
I am also interested in what happens when you add `--debug` to the command line. Do you see the log messages print out as the command runs, or is there a long delay followed by all of the messages being printed at the same time? Missing messages, or messages that are not printed until the end of the run indicate problems that would need to be fixed in backend invoke.

**Comment by thomscode** [comment]
I've been running this with a modified Drush on my local machine and unmodified on the remote. Doing it this way, the log messages do come back immediately. There is one message that is missing where drush calls `backend_invoke` on the remote end and isn't passing the information forward. 

I also ran `site-install` with `--debug` but redirected `STDERR` to `/dev/null`. This showed that there is definitely a difference between the log messages reported locally vs remote. The local log messages went directly to `STDERR` while the remote ones were redirected to `STDOUT`. Some of this is likely due to running the different versions of drush in the different locations. 

My next step is to see what the output is like when running a modified version of Drush on both remote and local.

**Comment by thomscode** [comment]
More work definitely needs done. After finally getting a modified version of Drush on the remote end, as well as local, the remote end doesn't report any of the log messages back to the local machine. :(

**Comment by greg-1-anderson** [comment]
It's likely that Drush is searching for the log packets on the stdout stream rather than the stdin stream. I'm not sure that backend invoke even bothers to send the stderr stream.

**Comment by thomscode** [comment]
My mistake, I forgot to use the debug flag.

Actually this is good results. I found one other location where `stderr` is redirected to `stdout` and commented both. When running this modification in both local and remote versions of drush it works great. There were some minor differences when running different versions of drush that caused some initial confusion but when I aligned the versions it worked nicely.

Going to run a couple more tests, and then submit the update and see what tests fail. Will continue on from there.

**Comment by simesy** [comment]
I'm getting this in with drush 9.3 and `drush @develop sql:dump > ~/Downloads/foo.sql`

```
<snip>
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-07-13  1:01:34
Connection to ssh.au.platform.sh closed.
```

Backend invoke is:
```
[command] Backend invoke: ssh -o PasswordAuthentication=no -t REDACTED-develop-sr3snxi--app@ssh.au.platform.sh '/app/vendor/bin/drush  --verbose --debug --alias-path=/Users/si/.drush/site-aliases --root=/app/web --uri=https://develop-sr3snxi-REDACTED.au.platformsh.site/  -vvv sql:dump 2>&1' 2>&1 [0.17 sec, 7.65 MB]
Calling proc_open(ssh -o PasswordAuthentication=no -t REDACTED-develop-sr3snxi--app@ssh.au.platform.sh '/app/vendor/bin/drush  --verbose --debug --alias-path=/Users/si/.drush/site-aliases --root=/app/web --uri=https://develop-sr3snxi-REDACTED.au.platformsh.site/  -vvv sql:dump 2>&1' 2>&1);
```

**Comment by greg-1-anderson** [comment]
The `Connection to ssh.au.platform.sh closed` is not under our control.

Ideally, we would support `drush sql:dump @develop --result-file=~/Downloads/foo.sql` (half of sql-sync); however, at the moment we do not. In the interim, you could perhaps hack it by piping the output through grep to remove that line.

**Comment by simesy** [comment]
(for the googles) The platform.sh guys recommend `platform db:dump -f ~/Downloads/foo.sql`

**Comment by weitzman** [comment]
This is fixed. Backend has been deprecated by new a new Process system in Drush 9.6.

**Comment by mikedotexe** [comment]
I wasn't able to get around this, so I added another step to our initial database import. My last line would always read: "Connection to {our-ip} closed." So I checked if the last line had "Connection" and removed it if so.

`if [ $(tail -n 1 db-from-server.sql | grep -c Connection) -eq 1 ]; then echo "Cleaning last line" && sed -i '' -e '$ d' db-from-server.sql; else echo "It's clean, did nothing."; fi`
