### ISSUE TITLE
Drush remote commands called twice (drush_do_command_redispatch() called twice) on 8.0.1

### ISSUE THREAD

**Issue by lklimek** [drush-ops/drush#1870]
Hi

I have the following configuration:
* 2 servers, "management" and "staging"
* both servers share the filesystem, and they have have the following directory structure:
  * /mnt/staging/vhosts/mysite/html contains Drupal8 
  * /var/www/vhosts is a symlink to /mnt/staging/vhosts 

On management, I have the following drush alias:
```
    $aliases["mysite"] = array (
        'root' => '/var/www/vhosts/mysite/html',
        'uri' => 'http://mysite.com',
        'remote-host' => '1.2.3.4',
        'remote-user' => 'root',
        'path-aliases' =>  array (
            '%drush-script' => '/usr/bin/drush8',
            '%drush' => '/usr/lib64/drush',
            '%site' => 'sites/default/',
        ),
   ...
```
My issue is that - when I run any remote command on management using mysite alias - it is executed twice:
```
[root@mgmt01 /]# drush @mysite version  -v
Loaded alias @mysite  from file              [notice]
/root/.drush/mysite.alias.drushrc.php
Begin redispatch via drush_invoke_process().                            [notice]
Calling proc_open(ssh -o PasswordAuthentication=no -t root@1.2.3.4 '/usr/bin/drush8  --root=/mnt/staging/vhosts/mysite/html --local --uri=http://mysite.com --verbose  version 2>&1' 2>&1);
Loading outputformat engine.                                            [notice]
 Drush Version   :  8.0.1

Command dispatch complete                                               [notice]
Connection to 1.2.3.4 closed.
End redispatch via drush_invoke_process().                              [notice]
Begin redispatch via drush_invoke_process().                            [notice]
Calling proc_open(ssh -o PasswordAuthentication=no root@1.2.3.4 '/usr/bin/drush8  --verbose --root=/var/www/vhosts/mysite/html --uri=http://mysite.com version 2>&1' 2>&1);
Loading outputformat engine.                                            [notice]
 Drush Version   :  8.0.1

Command dispatch complete                                               [notice]
End redispatch via drush_invoke_process().                              [notice]
```
The issue here is that condition in [line 567 of preflight.inc](https://github.com/drush-ops/drush/blob/3657fa99a9c47e4684786ccac71270b2db27615e/includes/preflight.inc#L567)  fails to correctly detect "remote" execution. 

My workaround is to add 'local' => 'false' to site alias definition, but I'm not sure if this is a "correct" resolution:
```
    $aliases["mysite"] = array (
        'root' => '/var/www/vhosts/mysite/html',
        'uri' => 'http://mysite.com',
        'remote-host' => '1.2.3.4',
        'remote-user' => 'root',
        'local' => 'false',
```
Note that you must pass 'false' as a string, not boolean, due to use of empty($is_local) in the if condition.

**Comment by weitzman** [comment]
No need to define %site or %drush. No idea if that matters.

**Comment by jmooring** [comment]
@lklimek 

Thank you for logging this issue back in 2015. And thank you for the `'local' => 'false'` solution!

I was struggling with the same problem (remote commands called twice) on a D7 site built using drupal-composer/drupal-project. Drush is not globally installed; it is required by composer/drupal-project. Instead of having to type `../vendor/bin/drush` from Drupal root, I installed drush-ops/drush-launcher on both the development (@dev) and production (@prd) systems.

Contents of /src/drush/site-aliases/aliases.drushrc.php on @dev:

```
$aliases['dev'] = array(
  'root' => '/home/foo/sites/www.example.com/src/web',
  'uri' => 'http://dev.www.example.com',
);
$aliases['prd'] = array(
  'remote-host' => 'www.example.com',
  'remote-user' => 'foo',
  'root' => '/home/foo/sites/www.example.com/src/web',
  'uri' => 'https://www.example.com',
);
```

There are no drush aliases files on @prd.

When I run `drush @dev --version` on dev system:

> Drush Launcher Version: 0.6.0
> Drush Version   :  8.1.16 

When I run `drush @prd --version` on dev system:

> Drush Launcher Version: 0.6.0
> Drush Version   :  8.1.16 
> 
> Connection to www.sunsethillsaa.org closed.
> Drush Launcher Version: 0.6.0
> Drush Version   :  8.1.16 

The command was run twice. This behavior causes `drush sql-sync @prd @dev` to fail, which is why I started looking into this in the first place.

Questions:

Is the need for `'local' => 'false'` documented anywhere? Other than carefully examining the code, I'm not sure how anyone would know about this parameter, or how to set it properly (i.e., requiring the string 'false' instead of the boolean).
Is the `local` parameter documented anywhere?
Should this issue be re-opened, or is there something unique to our installations that is triggering this behavior?

**Comment by weitzman** [comment]
Sounds like #3428 which was just fixed.

**Comment by jmooring** [comment]
I updated to 8.1.17-dev on both @dev and @prd using composer workflow, and removed `'local' => 'false'` from the @prd alias definition.

When I run `drush @dev --version` on dev system:

> Drush Launcher Version: 0.6.0
> Drush Version   :  8.1.17-dev 

When I run 'drush @prd --version` on dev system:

> Drush Launcher Version: 0.6.0
> Drush Launcher Version: 0.6.0
> Drush Version   :  8.1.17-dev 

The results are different than 8.1.16, but not what I would expect. And my original problem, the failure of `drush sql-sync @prd @dev`, still exists, and is fixed with `'local' => 'false'`.

However, even with `'local' => 'false'`, run 'drush @prd --version` on dev system still produces a duplicate:

> Drush Launcher Version: 0.6.0
> Drush Launcher Version: 0.6.0
> Drush Version   :  8.1.17-dev 

So my `drush sql-sync @prd @dev` problem and the problem fixed by #3428 may be related, but is not the same.
