### ISSUE TITLE
drush si --locale breaks on D7

### ISSUE THREAD

**Issue by nvaken** [drush-ops/drush#2345]
Porting this from a older issue on Drupal.org: https://www.drupal.org/node/1297438. Following content has been copied from my comment on that issue (somewhat adjusted). I'd like to followup on this. 

==========================

After a year / few years of frustration, I stopped frustrating and started to debug this.

# The problem
When running `drush site-install` with the `--locale` option the installer will be translated, including the "forms" that are being (mis)used to run the Drupal installer (install.core.inc). This includes the 'save' action-button in the `install_settings_form` which is (in Dutch) being translated from `Save and continue` to `Opslaan en doorgaan`. This is a UI thing, which needs to happen for the user that is using the web-interface, which is all rainbows and sunshine in that setup, but when using Drush it will not work out properly.

The button uses `#limit_validation_errors` to limits error validation to only the selected database type (see code below). The problem is, this functionality will only trigger on `triggering_element`(see form.inc line 1196) which is the element that has been clicked to submit the form. In the function `_form_button_was_clicked()` the form system will attempt to find out which button has been clicked, but at this point it will not be able to do so, since there is now a inconsistency in a untranslated form_state value and element value.

```
    '#limit_validation_errors' => array(
      array('driver'),
      array(isset($form_state['input']['driver']) ? $form_state['input']['driver'] : current($drivers_keys)),
    ),
```

# Possible solution
I THINK the fix should be applied in core, but I would like to discuss it here first before doing so. My current solution simply checks if the `$install_state` is interactive or not. If it's non-interactive, it makes sure the button is not being translated. See attached patch.

For me this feels like more of a workaround then a solid fix. I'm seeing a lot of other possibilities, though I'm not sure which would be the best and am hoping that someone is able to come up with a solid fix after this complete debug story. 

Again, I'd like to add that my proposed fix does not apply to Drush but instead applies to Drupal core. I'm still adding this issue here, since I think this found it's origins in Drush. Also, I'm really wondering if using the Drupal core setup forms to install Drupal is really the way to go. Shouldn't Drush install Drupal through decent functions without imitating form submissions? Probably not possible atm, but shouldn't there be a feature request on Drupal core on that matter then?

I do feel like this is still a hefty issue and should definately be fixed and hope that others are willing to help out on this regard.

Thanks.

[possible-fix--core--1297438.txt](https://github.com/drush-ops/drush/files/479889/possible-fix--core--1297438.txt)

**Comment by weitzman** [comment]
Drush doesn't use forms during site-install. It simply calls the D8 unction`install_drupal()`. Sorry I have no more input on this issue.

**Comment by nvaken** [comment]
Hi @weitzman, 

Thanks for your reply. 

We might have a miscommunication about which version of Drupal core this is about: `7.x` (see issue title).

That being said... I agree on your observation that drush uses `install_drupal()`, though, it does seem to mimic the forms which are needed by `install_drupal()`. See the `$settings` array which is being defined in `commands/core/drupal/site_install_7.inc`:

```
  $settings = array(
    'parameters' => array(
      'profile' => $profile,
      'locale' => drush_get_option('locale', 'en'),
    ),
    'forms' => array(
      'install_settings_form' => array(
        'driver' => $db_spec['driver'],
        $db_spec['driver'] => $db_spec,
        'op' => dt('Save and continue'),
      ),
      'install_configure_form' => array(
        'site_name' => drush_get_option('site-name', 'Site-Install'),
        'site_mail' => drush_get_option('site-mail', 'admin@example.com'),
        'account' => array(
          'name' => $account_name,
          'mail' => drush_get_option('account-mail', 'admin@example.com'),
          'pass' => array(
            'pass1' => $account_pass,
            'pass2' => $account_pass,
          ),
        ),
        'update_status_module' => array(
          1 => TRUE,
          2 => TRUE,
        ),
        'clean_url' => drush_get_option('clean-url', TRUE),
        'op' => dt('Save and continue'),
      ),
    ),
  );
```

This even injects the correct values for the submit buttons in between the steps between the forms.

Again, I do feel like this is a bit of a sluggish solution, but I assume that Drupal 7 core simply does not allow for install without form settings. Therefor I think this should be solved in core.

**Comment by urbantom** [comment]
The problem still exists in D8. Cost: about one week of investigation.
