### ISSUE TITLE
Error fwrite() expects parameter 1 to be resource, string given in includes/output.inc</b> on line <b>35</b><br />

### ISSUE THREAD

**Issue by jomarocas** [drush-ops/drush#2747]
Hi i have this error in terminal

`Error fwrite() expects parameter 1 to be resource, string given in includes/output.inc</b> on line <b>35</b><br />`

i install drush 7x, centos 6x, i cannot install pear then i cannot install with pear and composer also have problems to install. 

i download the tree 7x and unzip, this is for shared hosting.
i add this line in bash_profile
```
export COLUMNS
alias drush='/usr/bin/php ~/drush/drush.php --php=/usr/bin/php'
alias php='/usr/bin/php'
```
I write drush and the next message appear

i receive this message 

```
X-Powered-By: PHP/5.6.30
Content-type: text/html; charset=UTF-8

Execute a drush command. Run `drush help [command]` to view command-specific help. 
Run `drush topic` to read even more documentation.
```

later drush cc all

```
X-Powered-By: PHP/5.6.30
Content-type: text/html; charset=UTF-8

<br />
<b>Fatal error</b>:  Cannot redeclare drush_print_help() (previously declared in ~/drush/commands/core/help.drush.inc:36) in <b>~/public_html/drush/commands/core/helpsingle.drush.inc</b> on line <b>119</b><br />
<br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, string given in <b>~/drush/includes/output.inc</b> on line <b>35</b><br />
<br />
<b>Warning</b>:  fwrite() expects parameter 1 to be resource, string given in <b>~/drush/includes/output.inc</b> on line <b>35</b><br />
```
Thanks for any advice or solution of this message

**Comment by kenrbnsn** [comment]
Instead of closing this without a comment, perhaps an explanation should have been given. I started getting these messages after upgrading php to v5.6 on my cPanel host. After much investigating, I discovered that the php being run from the command line was the cgi version, not the cli version. Once I fixed the path to use the cli version, these message went away. 

What gave me the hint I needed, was this thread: https://www.drupal.org/node/1064690

**Comment by jomarocas** [comment]
@kenrbnsn Hey thanks for the comments, but how make this in my vps host, i verify php version and cli version are updated, but this message still appear

**Comment by damienmckenna** [comment]
FYI, for anyone who runs into this.. I hit this problem on CPanel server and fixed it by renaming the /bin/php command out of the way and then symlinking /usr/local/bin/php in its place:

```
$ sudo su
$ mv /bin/php /bin/php_
$ ln -s /usr/local/bin/php /bin/php
```
After that change I was able to run drush commands without the errors.

Disclaimer: this was done using the "root" user, I'm not responsible if you break your server following the commands above, speak with an experienced server admin before you start changing things on a server.
