### ISSUE TITLE
Handle missing PHP posix fuctions - was drush sql:cli (sqlc) hangs when executing mysql client command (9.6.1)

### ISSUE THREAD

**Issue by Zekvyrin** [drush-ops/drush#4027]
I'm trying to execute 'drush sqlc' command but the execution is hanging there, not doing anything no matter how long I wait.

This is happening in a specific server, that is managed, not my local machine. The site project runs normally on my local machine. I have no clue why is this happening, 

>$ drush sqlc --debug
>Drush Launcher Version: 0.6.0
>ROOT: [folder_path]
>DRUSH VERSION: 9
>DRUPAL ROOT: [folder_path]/web
>COMPOSER ROOT: [folder_path]
>VENDOR ROOT: [folder_path]/vendor
>[preflight] Config paths: [folder_path]/vendor/drush/drush/drush.yml,[folder_path]/drush/drush.yml
>[preflight] Alias paths: [folder_path]/web/drush/sites,[folder_path]/drush/sites
>[preflight] Commandfile search paths: [folder_path]/vendor/drush/drush/src,[folder_path]/drush
>[bootstrap] Starting bootstrap to max [0.13 sec, 3.37 MB]
>[bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.13 sec, 3.37 MB]
>[bootstrap] Change working directory to [folder_path]/web [0.13 sec, 3.37 MB]
>[bootstrap] Initialized Drupal 8.6.13 root directory at [folder_path]/web [0.13 sec, 3.38 MB]
>[bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.14 sec, 3.46 MB]
>[bootstrap] Initialized Drupal site default at sites/default [0.14 sec, 3.53 MB]
>[bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.14 sec, 3.53 MB]
>[debug] Add service modifier [0.14 sec, 3.62 MB]
>[info] Executing: command -v mysql [0.15 sec, 3.79 MB]
>[info] Executing: mysql --defaults-file=/tmp/drush_bF5arJ --database=[dbname] --host=localhost --port=3306 -A [0.16 sec, 3.81 MB]

(it just stops there)

Now if I try to run the last command
`mysql --defaults-file=/tmp/drush_bF5erJ --database=[dbname] --host=localhost --port=3306 -A` 
It will run normally...

I use drush-launcher, but also tried it without ( by calling [folder_path]/vendor/drush/drush/drush), still hangs.

>$ drush status 
> Drupal version : 8.6.13 
> Site URI : http://default 
> DB driver : mysql 
> DB hostname : localhost 
> DB port : 3306 
> DB username : [dbname] 
> DB name : [dbuser] 
> Database : Connected 
> Drupal bootstrap : Successful 
> Default theme : [] 
> Admin theme : seven 
> PHP binary : /usr/bin/php 
> PHP config : /etc/php.ini 
> PHP OS : Linux 
> Drush script : /home/[username]/bin/drush.phar 
> Drush version : 9.6.1 
> Drush temp : /tmp 
> Drush configs : [folder_path]/vendor/drush/drush/drush.yml 
> [folder_path]/drush/drush.yml 
> Install profile : standard 
> Drupal root : [folder_path]/web 
> Site path : sites/default 
> Files, Public : sites/default/files 
> Files, Private : ../privatefiles/ 
> Files, Temp : /tmp 

On the contrary, if I use globally installed drush (8.1.3) [i need to uninstall drush 9 from the project todo that] the command runs normally. (but using this is not convenient)

> $ drush sqlc --debug
> Drush Launcher Version: 0.6.0
> ROOT: [folder_path]/web
> DRUSH VERSION: 
> DRUPAL ROOT: [folder_path]/web
> COMPOSER ROOT: [folder_path]
> VENDOR ROOT: [folder_path]/vendor
> Calling fallback: /usr/local/bin/drush 'sqlc' '--debug'
> Phar detected. Proceeding to drush_main().Cache HIT cid: 8.1.3-commandfiles-0-e7a42d5ca6307ff8e91f3657f6a2806f [0.01 sec, 1.33 MB] [debug]
> Bootstrap to phase 0. [0.09 sec, 2.82 MB] [bootstrap]
> Bootstrap to phase -1. [0.09 sec, 2.82 MB] [bootstrap]
> Found command: sql-cli (commandfile=sql) [0.09 sec, 2.82 MB] [bootstrap]
> Calling hook drush_sql_cli [0.09 sec, 2.88 MB] [debug]
> Drush bootstrap phase : bootstrap_drupal_root() [0.11 sec, 3.09 MB] [bootstrap]
> Initialized Drupal 8.6.13 root directory at [folder_path]/web [0.11 sec, 3.09 MB] [bootstrap]
> Find command files for phase 1 (max=3) [0.11 sec, 1.96 MB] [debug]
> Cache HIT cid: 8.1.3-commandfiles-1-c628a6d0cacbc67a4f33f8abd8e2b027 [0.11 sec, 1.96 MB] [debug]
> Cache HIT cid: 8.1.3-annotationfiles-1-66a6f25af40c739732dc5ba2c18b5af8 [0.11 sec, 1.96 MB] [debug]
> Drush bootstrap phase : bootstrap_drupal_site() [0.15 sec, 2.08 MB] [bootstrap]
> Initialized Drupal site default at sites/default [0.15 sec, 2.08 MB] [bootstrap]
> Find command files for phase 2 (max=3) [0.15 sec, 2.08 MB] [debug]
> Cache MISS cid: 8.1.3-install_profile-66ecfeb9791a023150773849f1550c5d [0.15 sec, 2.08 MB] [debug]
> Cache HIT cid: 8.1.3-commandfiles-2-695cb0f2778f0a6220e1378e080ff362 [0.15 sec, 2.09 MB] [debug]
> Drush bootstrap phase : bootstrap_drupal_configuration() [0.15 sec, 2.15 MB] [bootstrap]
> Create from request [0.16 sec, 2.19 MB] [debug]
> add service modifier [0.16 sec, 2.21 MB] [debug]
> Find command files for phase 3 (max=3) [0.16 sec, 2.21 MB] [debug]
> Calling proc_open(mysql --defaults-extra-file=/tmp/drush_wfb8TI --database=dbname --host=localhost --port=3306);
> Reading table information for completion of table and column names
> You can turn off this feature to get a quicker startup with -A
> 
> Welcome to the MariaDB monitor. Commands end with ; or \g.
> Your MariaDB connection id is 1635960
> Server version: 10.1.37-MariaDB MariaDB Server
> 
> Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> MariaDB [dbname]> 

As I mentioned the server is managed, and the admin mentioned:
> it seems drush is waiting for the mysql-client to become ready:
> 
> 16699 select(10, [], [9], [], {0, 0}) = 1 (out [9], left {0, 0})
> 16699 read(0, 0x7f19ba01a000, 8192) = -1 EAGAIN (Resource temporarily unavailable)
> 16699 select(13, [10 12], [], [], {0, 200000}) = 0 (Timeout)
> 
> I see the connection on the mysql processlist - so it is there.

So... I'm out of ideas. It works perfectly fine in my local computer (intentionally running same php version). Any help?

Thank you

**Comment by greg-1-anderson** [comment]
It could be that your tty isn't set up correctly; Drush might be confused & using the wrong mode. In the failing case, try typing `select * from users;` <RETURN> <CONTROL-D> and see if it outputs something.

**Comment by weitzman** [comment]
I saw hanging like that with older versions of Drush but I have not seen it with 9.6. You are seeing the opposite (drush8 works but drush 9.6 does not). I cant explain that.

**Comment by Zekvyrin** [comment]
@greg-1-anderson no the query doesn't do anything. Is there anything else I can try?

All other commands I've tried are working (sql:drop, sql:dump, sqlq, sql:connect).

**Comment by greg-1-anderson** [comment]
Did you press RETURN and CONTROL-D after you typed the SQL? I accidentally typed those instructions with `<>`, so GitHub hid them (as unknown HTML tags). I edited my advice.

**Comment by greg-1-anderson** [comment]
We fixed a couple of process bugs in Drush 9.6.2. I don't know that either of them would be in play here, but you could try the upgrade and see.

**Comment by Zekvyrin** [comment]
oh... if I do that, it outputs the user table and ends the command.

Basically the export is the same like if I typed
`drush sqlq 'select * from users'` 
with 1 extra line
"uid	uuid	langcode"

(No sadly 9.6.2 doesn't fix this)

**Comment by greg-1-anderson** [comment]
How about `drush -Dssh.tty=0 sqlc --debug`

**Comment by greg-1-anderson** [comment]
Actually, the advice above will not help. The problem is that Drush 9.6 is *not* creating a tty for you, whereas Drush 8 is. I'm not sure why.

**Comment by greg-1-anderson** [comment]
Just tried to reproduce this, and it works fine for me with both Drush 8 and Drush 9 on a locally-installed Drupal site.

**Comment by Zekvyrin** [comment]
I cannot reproduce it either on my local machine (using same php version -7.1- and same project/files)
It's only happening in that machine.

**Comment by greg-1-anderson** [comment]
Does the other machine have the `posix_isatty` function? Not all PHP installs come with the posix functions. TTY support won't necessarily work right without it.

It's possible to turn off TTYs with `-Dssh.tty=0`. A PR to force TTY usage on with `-Dssh.tty=1` would be welcome.

**Comment by Zekvyrin** [comment]
@greg-1-anderson 

I'll quote my admin:
> Thank you for the hint - php-process package was missing.

It works fine now. Thanks a lot! :+1:

**Comment by Zekvyrin** [comment]
Hm.. maybe it could be added as a drush requirement or a warning that this is missing?

(just to help others with a similar issue)

**Comment by weitzman** [comment]
Reopening and retitling so we remember to handle this better.

Also, site:set depends on posix function as well.

**Comment by greg-1-anderson** [comment]
We don't need the posix functions if we use https://github.com/drush-ops/drush/pull/4033 everywhere.

**Comment by greg-1-anderson** [comment]
Oh, right, we still need different posix functions for `site:set` as mentioned above.

**Comment by weitzman** [comment]
site:set already has `@validate-php-extension posix`. I think we are done here.
